task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

# num_classes: 80
num_classes: 8
remap_mscoco_category: True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /root/autodl-tmp/aitod/images/train/
    ann_file: /root/autodl-tmp/aitod/annotations/aitodv2_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 0
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /root/autodl-tmp/aitod/images/trainval/
    ann_file: /root/autodl-tmp/aitod/annotations/aitodv2_trainval.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 0
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
